name: Test Checker
on: push
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install
        run: |
          sudo apt update
          sudo apt install -y g++
          
      - name: Get
        run: g++ -o app app.cpp
        
      - name: Checker
        run: bash tests/test.sh
      
